routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('crud', 'CrudsController');

app/Crud.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Crud extends Model
{
    protected $table = 'contacts';

    protected $fillable = [
        'first_name', 'last_name', 'image'
    ];
}

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/CrudsController.php
<?php

namespace App\Http\Controllers;

use App\Crud;
use Illuminate\Http\Request;

class CrudsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = Crud::latest()->paginate(5);
        return view('index', compact('data'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'first_name' => 'required',
            'last_name' => 'required',
            'image' => 'required|image|max:2048'
        ]);

        $image = $request->file('image');

        $new_name = rand() . '.' . $image->getClientOriginalExtension();
        $image->move(public_path('images'), $new_name);
        $form_data = array(
            'first_name' => $request->first_name,
            'last_name' => $request->last_name,
            'image' => $new_name
        );

        Crud::create($form_data);

        return redirect('crud')->with('success', 'Data Added successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = Crud::findOrFail($id);
        return view('view', compact('data'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $data = Crud::findOrFail($id);
        return view('edit', compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $image_name = $request->hidden_image;
        $image = $request->file('image');
        if ($image != '') {
            $request->validate([
                'first_name' => 'required',
                'last_name' => 'required',
                'image' => 'image|max:2048'
            ]);

            $image_name = rand() . '.' . $image->getClientOriginalExtension();
            $image->move(public_path('images'), $image_name);
        } else {
            $request->validate([
                'first_name' => 'required',
                'last_name' => 'required'
            ]);
        }

        $form_data = array(
            'first_name' => $request->first_name,
            'last_name' => $request->last_name,
            'image' => $image_name
        );

        Crud::whereId($id)->update($form_data);

        return redirect('crud')->with('success', 'Data is successfully updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $data = Crud::findOrFail($id);
        $data->delete();

        return redirect('crud')->with('success', 'Data is successfully deleted');
    }
}

resources/views/create.blade.php
@extends('parent')

@section('main')
    @if($errors->any())
        <div class="alert alert-danger">
            <ul>
                @foreach($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif
    <div align="right">
        <a href="{{ route('crud.index') }}" class="btn btn-default">Back</a>
    </div>

    <form method="post" action="{{ route('crud.store') }}" enctype="multipart/form-data">

        @csrf
        <div class="form-group">
            <label class="col-md-4 text-right">Enter First Name</label>
            <div class="col-md-8">
                <input type="text" name="first_name" class="form-control input-lg"/>
            </div>
        </div>
        <br/>
        <br/>
        <br/>
        <div class="form-group">
            <label class="col-md-4 text-right">Enter Last Name</label>
            <div class="col-md-8">
                <input type="text" name="last_name" class="form-control input-lg"/>
            </div>
        </div>
        <br/>
        <br/>
        <br/>
        <div class="form-group">
            <label class="col-md-4 text-right">Select Profile Image</label>
            <div class="col-md-8">
                <input type="file" name="image"/>
            </div>
        </div>
        <br/><br/><br/>
        <div class="form-group text-center">
            <input type="submit" name="add" class="btn btn-primary input-lg" value="Add"/>
        </div>

    </form>

@endsection

resources/views/edit.blade.php
@extends('parent')

@section('main')
    <div align="right">
        <a href="{{ route('crud.index') }}" class="btn btn-default">Back</a>
    </div>
    <br/>

    <form method="post" action="{{ route('crud.update', $data->id) }}" enctype="multipart/form-data">

        @csrf
        @method('PATCH')
        <div class="form-group">
            <label class="col-md-4 text-right">Enter First Name</label>
            <div class="col-md-8">
                <input type="text" name="first_name" value="{{ $data->first_name }}" class="form-control input-lg"/>
            </div>
        </div>
        <br/>
        <br/>
        <br/>
        <div class="form-group">
            <label class="col-md-4 text-right">Enter Last Name</label>
            <div class="col-md-8">
                <input type="text" name="last_name" value="{{ $data->last_name }}" class="form-control input-lg"/>
            </div>
        </div>
        <br/>
        <br/>
        <br/>
        <div class="form-group">
            <label class="col-md-4 text-right">Select Profile Image</label>
            <div class="col-md-8">
                <input type="file" name="image"/>
                <img src="{{ URL::to('/') }}/images/{{ $data->image }}" class="img-thumbnail" width="100"/>
                <input type="hidden" name="hidden_image" value="{{ $data->image }}"/>
            </div>
        </div>
        <br/><br/><br/>
        <div class="form-group text-center">
            <input type="submit" name="edit" class="btn btn-primary input-lg" value="Edit"/>
        </div>
    </form>
@endsection

resources/views/index.blade.php
@extends('parent')

@section('main')

    <div align="right">
        <a href="{{ route('crud.create') }}" class="btn btn-success btn-sm">Add</a>
    </div>
    <br/>
    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif


    <table class="table table-bordered table-striped">
        <tr>
            <th width="10%">Image</th>
            <th width="35%">First Name</th>
            <th width="35%">Last Name</th>
            <th width="30%">Action</th>
        </tr>
        @foreach($data as $row)
            <tr>
                <td><img src="{{ URL::to('/') }}/images/{{ $row->image }}" class="img-thumbnail" width="75"/></td>
                <td>{{ $row->first_name }}</td>
                <td>{{ $row->last_name }}</td>
                <td>

                    <form action="{{ route('crud.destroy', $row->id) }}" method="post">
                        <a href="{{ route('crud.show', $row->id) }}" class="btn btn-primary">Show</a>
                        <a href="{{ route('crud.edit', $row->id) }}" class="btn btn-warning">Edit</a>
                        @csrf
                        @method('DELETE')
                        <button type="submit" class="btn btn-danger">Delete</button>
                    </form>
                </td>
            </tr>
        @endforeach
    </table>
    {!! $data->links() !!}
@endsection

resources/views/parent.blade.php
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Laravel 7 Crud Tutorial</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1' name='viewport'/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet"/>
</head>
<body>
<div class="container">
    <br/>
    <h3 align="center">Laravel 7 Crud Tutorial</h3>
    <br/>
    @yield('main')
</div>
</body>
</html>

resources/views/view.blade.php
@extends('parent')

@section('main')

    <div class="jumbotron text-center">
        <div align="right">
            <a href="{{ route('crud.index') }}" class="btn btn-default">Back</a>
        </div>
        <br/>
        <img src="{{ URL::to('/') }}/images/{{ $data->image }}" class="img-thumbnail"/>
        <h3>First Name - {{ $data->first_name }} </h3>
        <h3>Last Name - {{ $data->last_name }}</h3>
    </div>
@endsection